### ISSUE TITLE
UploadStream to Azure Blob Storage Fails

### ISSUE THREAD

**Issue by ttfreeman** [pliancy/intune-node#124]
uploadToAzureBlob function is failing at blockBlobClient.uploadStream(file, bufferSize, 5). I have confirmed all the steps above the uploadStrem() are successful. This is the error message:

TypeError: _this.readable.on is not a function
    at /home/??????/node_modules/@azure/storage-blob/src/utils/BufferScheduler.ts:237:21
....
...
 at BlockBlobClient.uploadStream (/home/????????/node_modules/@azure/storage-blob/dist/index.js:14813:22)

**Comment by ttfreeman** [comment]
Hi @santese . Any idea why this error is happening? I am guessing it is because of the project requires unencrypted intunewin file rather than the intunewin file itself? Do we have a function in the project to decrypt the intunewin file?

**Comment by santese** [comment]
@ttfreeman, I actually use powershell myself to decrypt and pull out all of the necessary info. I can make a gist and send over how i do it. 

Also i made an issue to support uploading the encrypted .intunewin files. We'll be working on that soon #125

**Comment by ttfreeman** [comment]
Thanks @santese . Integrating a powershell in nodejs code wouldn't be ideal but I can test using the decrypted intunewin file when I receive your script if that solves the upload issue. I will be happy to help you with the new issue you created. I will comment there.
